### PR TITLE
fix sample to use Call

### PR DESCRIPTION
**Pull request by mhdawson**
In this example we should be using Call not
MakeCallback. Update to be consistent with the
napi example

### CODE REVIEW

**Comment by mhdawson** [comment]
@NickNaso can you take a look and review?

**Review by NickNaso — COMMENTED** [review]
Hi @mhdawson the code is good to me. 
Generally speaking I have some considerations about the examples.
Should we use *NODE_GYP_MODULE* instead of the name of the module placed on the *gyp* file?
In the `package.json` should we use the latest version of *node-addon-api* and *bindings* module?  
```
{
  "dependencies": {
     "node-addon-api": "*",
     "bindings": "*"
  }
}
```
If you agree we can start from this example and make these changes for all examples.

**Comment by mhdawson** [comment]
@NickNaso I think the changes you suggest make sense, but I think it would be good to make then to all of the examples together as opposed to making the change in this PR.

I'll go ahead and land this one and then you can open a PR for the other changes.

**Comment by mhdawson** [comment]
Landed as 75ee5e529fad35007f91c7446c7fd16db1ba8af2

**Pull request closed without merging**
