### PR TITLE
Emit event from cpp with libuv and napi

### PR DESCRIPTION
**Pull request by DayBr3ak**
This PR shows one way to use native threads to generate events for node.

This example is not blocking

Events are queue'd up by the native threads and consumed by nodejs libuv loop.

### CODE REVIEW

**Comment by mhdawson** [comment]
@gabrielschulhof can you take a look as we may want to align with https://github.com/nodejs/node/pull/17887

**Comment by mhdawson** [comment]
@gabrielschulhof can  you take a look at we should make sure it aligns with your work on the tfsa

**Comment by mhdawson** [comment]
@gabrielschulhof actually this should be moved to https://github.com/nodejs/node-addon-examples Right? We should archive the abi-stable-node-addon-examples repo as we moved over to using node-addon-examples instead.

**Comment by gabrielschulhof** [comment]
@mhdawson @DayBr3ak yes, this should be moved to node-addon-examples.

**Comment by mhdawson** [comment]
@DayBr3ak I'm going to close this in preparation of archiving the repo.  If you are still able to work on this please submit pr to https://github.com/nodejs/node-addon-examples repo.

**Pull request closed without merging**
